CREATE TABLE Messages (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  pseudo VARCHAR(40) NOT NULL,
  message TEXT NOT NULL,
  date_message DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;